name: Build news sitemap

on:
  schedule:
    - cron: "0 * * * *"      # runs hourly
  workflow_dispatch: {}       # lets you run it by hand

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build sitemap
        run: python build_news_sitemap.py

      - name: Commit if changed
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add news-sitemap.xml
            git commit -m "Auto-update news-sitemap.xml"
            git push
          else
            echo "No changes"
          fi
